#!/usr/bin/env /usr/bin/python3

# ----- Imports ---------------------------------------------------------------

from tinyAPI.base.services.cli import cli_main
from tinyAPI.base.services.unit_testing import Manager

import os
import subprocess
import tinyAPI

# ----- Main ------------------------------------------------------------------

def main(cli):
    cli.header('Unit Tests')

    utm = Manager(cli)
    files = subprocess.check_output(
                "/usr/bin/find "
                + os.getcwd()
                + "/* -name \"*.py\" | /bin/grep \"/tests/\"; "
                + "exit 0",
                stderr=subprocess.STDOUT,
                shell=True).decode()
    utm.execute(files.split("\n"))

    utm.print_summary()

# ----- Instructions ----------------------------------------------------------

cli_main(main)
