#!/usr/bin/env /usr/bin/python3

# ----- Imports ---------------------------------------------------------------

from tinyAPI.base.config import ConfigManager
from tinyAPI.base.services.cli import cli_main
from tinyAPI.base.services.unit_testing import Manager

import os
import subprocess
import tinyAPI

# ----- Main ------------------------------------------------------------------

def main(cli):
    cli.header('Unit Tests')

    utm = Manager(cli)
    paths = ConfigManager().value('application dirs')
    for path in paths:
        files = subprocess.check_output(
                    "/usr/bin/find "
                    + path
                    + "/* -name \"*.py\" | /bin/grep \"/tests/\"; "
                    + "exit 0",
                    stderr=subprocess.STDOUT,
                    shell=True).decode()
        utm.execute(files.split("\n"))

    utm.print_summary()

# ----- Instructions ----------------------------------------------------------

cli_main(main)
