#!/usr/bin/env python3

# ----- Imports --------------------------------------------------------------

from subprocess import check_output
from tinyAPI.base.config import ConfigManager
from tinyAPI.base.services.cli import cli_main
from tinyAPI.base.services.unit_testing import Manager
import os
import tinyAPI

# ----- Main -----------------------------------------------------------------

def main(cli):
    cli.header('Unit Tests')

    utm = Manager(cli)
    paths = ConfigManager().value('unit test paths')
    for path in paths:
        files = check_output("/usr/bin/find "
                             + path
                             + "/* -name \"*.py\" | /bin/grep \"/tests/\"",
                             shell=True).decode()
        utm.execute(files.split("\n"))

    utm.print_summary()

# ----- Instructions ---------------------------------------------------------

cli_main(main)
